name: Run Pipeline

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master
jobs:
  ci:
    name: Run tests and static analysis
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Prepare environment
        run: |
          cp .env.example .env
          php artisan key:generate

          echo "REDIS_HOST=redis" >> .env
          echo "DB_HOST=127.0.0.1" >> .env

      - name: Wait for Redis
        run: |
          for i in 1 2 3 4 5; do
            nc -z -w 1 redis 6379 && exit 0
            echo "Waiting for Redis... (Attempt $i/5)"
            sleep 3
          done
          echo "Redis failed to start or connect after 5 attempts."
          exit 1

      - name: Run PHPUnit tests
        run: composer test

      - name: Run Laravel Pint
        run: composer cs-fixer

      - name: Run PHPStan analysis
        run: composer analyse
